"""Regression tests against Table 1 of the TOF paper.

Benkő, Bábel, Somogyvári: "How to find a unicorn", Sci. Rep. 12:227 (2022),
doi 10.1038/s41598-021-03526-y (arXiv:2004.11468, Supporting Information
section "Generation of simulated datasets").

Each simulated dataset is regenerated from scratch, TOF is run with the
embedding (E=3, tau=1) and the neighbour count k reported in Table 1, and the
ROC AUC of the TOF score is averaged over N_SEEDS realisations. The mean must
be within TOLERANCE of the published value.

Data-generation conventions follow the CSV files the authors published with the
package (examples/data/simulations), which reproduce Table 1 to three decimals
when run through this same pipeline:

* anomaly length is drawn uniformly from 20-200 samples (main text; the SI
  text says 2-200 but the published files use 20-200);
* the logistic-map datasets are generated by the package's own
  ``generate_logmapdata`` loop structure, so the first labelled sample is the
  first one produced by the anomalous update rule;
* the random walk is analysed after log-differencing, as in the paper.

The simulated-ECG dataset (Table 1 row "sim ECG-tachy", AUC 0.931) is skipped:
the Ryzhii & Ryzhii ECG model has no generator in this repository.
"""

import numpy as np
import pandas as pd
import pytest
from sklearn.metrics import roc_auc_score

from uniqed.data.gen_logmap import basic, generate_logmapdata
from uniqed.runners.tof_run import detect_outlier

SERIES_LENGTH = 2000
ANOMALY_LENGTH_MIN = 20
ANOMALY_LENGTH_MAX = 200
EMBEDDING_DIMENSION = 3
EMBEDDING_DELAY = 1
N_SEEDS = 100
TOLERANCE = 0.02

# Linear insert: x_{t+1} = x_t + a * x_t with a = +-0.001, reflective in (0, 1)
LINEAR_SLOPE = 0.001
# Multiplicative random walk: w_i ~ N(mu, sigma), x_i = prod_{j<=i} (1 + w_j)
RANDOM_WALK_MEAN = 0.001
RANDOM_WALK_SD = 0.01

# Table 1, TOF columns: (dataset, k, ROC AUC)
TABLE_1 = {
    "logmap-tent": (2, 0.939),
    "logmap-linear": (6, 0.994),
    "sim-ECG-tachy": (2, 0.931),
    "randwalk-linear": (30, 0.988),
}


def _draw_anomaly_window(rng, n):
    """Length and start of the anomalous segment, uniform as in the SI."""
    length = rng.randint(ANOMALY_LENGTH_MIN, ANOMALY_LENGTH_MAX)
    start = rng.randint(n - length)
    return length, start


def generate_logmap_tent(seed):
    """Logistic map (r=3.9) with a tent-map insert. Package generator."""
    return generate_logmapdata(N=SERIES_LENGTH, rseed=seed)


def generate_logmap_linear(seed):
    """Logistic map (r=3.9) with a low-gradient linear insert (SI Eq. 25).

    Mirrors the loop of ``generate_logmapdata`` so the label alignment is the
    same as in the published tent-map data; only the anomalous update differs.
    """
    rng = np.random.RandomState(seed)
    length, start = _draw_anomaly_window(rng, SERIES_LENGTH)

    slope = LINEAR_SLOPE
    x = [rng.rand()]
    truth = []
    for q in range(SERIES_LENGTH):
        if start < q < start + length:
            x_new = x[-1] + slope * x[-1]
            if not 0.0 < x_new < 1.0:
                slope = -slope
                x_new = x[-1] + slope * x[-1]
            x.append(x_new)
            truth.append(1)
        else:
            x.append(basic(x[-1]))
            truth.append(0)

    return pd.DataFrame({"value": np.array(x)[1:], "is_anomaly": truth})


def generate_randwalk_linear(seed):
    """Multiplicative random walk with a linear insert (SI, random walk data).

    Returns the raw walk; the caller log-differences it before detection.
    """
    rng = np.random.RandomState(seed)
    w = rng.normal(RANDOM_WALK_MEAN, RANDOM_WALK_SD, SERIES_LENGTH)
    x = np.cumprod(1.0 + w)

    length, start = _draw_anomaly_window(rng, SERIES_LENGTH)
    end = start + length
    x[start:end] = np.linspace(x[start], x[end - 1], length)

    truth = np.zeros(SERIES_LENGTH, dtype=int)
    truth[start:end] = 1
    return pd.DataFrame({"value": x, "is_anomaly": truth})


def log_difference(data_df):
    """Stationarising preprocessing used in the paper for the random walk."""
    value = np.diff(np.log(data_df["value"].values))
    is_anomaly = data_df["is_anomaly"].values[1:]
    return pd.DataFrame({"value": value, "is_anomaly": is_anomaly})


def tof_roc_auc(data_df, k):
    """ROC AUC of the TOF score against the ground-truth labels.

    Lower TOF means more anomalous, so the negated score is the ranking
    statistic. Rows without a score (the embedding edge) are dropped.
    """
    res_df = detect_outlier(
        data_df[["value"]],
        cutoff_n=ANOMALY_LENGTH_MAX,
        k=k,
        embedding_dimension=EMBEDDING_DIMENSION,
        embedding_delay=EMBEDDING_DELAY,
    )
    scored = res_df["TOF_score"].notna().values
    y_true = data_df["is_anomaly"].values[scored]
    y_score = -res_df["TOF_score"].values[scored]
    return roc_auc_score(y_true, y_score)


DATASETS = {
    "logmap-tent": generate_logmap_tent,
    "logmap-linear": generate_logmap_linear,
    "randwalk-linear": lambda seed: log_difference(generate_randwalk_linear(seed)),
}


@pytest.mark.parametrize("name", list(DATASETS))
def test_roc_auc_matches_table_1(name):
    k, expected_auc = TABLE_1[name]
    aucs = [tof_roc_auc(DATASETS[name](seed), k) for seed in range(N_SEEDS)]
    mean_auc = float(np.mean(aucs))
    assert abs(mean_auc - expected_auc) <= TOLERANCE, (
        f"{name}: mean ROC AUC over {N_SEEDS} seeds is {mean_auc:.3f}, "
        f"Table 1 reports {expected_auc:.3f} (tolerance {TOLERANCE})"
    )


def test_sim_ecg_tachy_not_reproducible_here():
    pytest.skip(
        "sim-ECG-tachy (Table 1 AUC 0.931) needs the Ryzhii & Ryzhii ECG "
        "generator, which does not exist in this repository"
    )
